#!/usr/bin/env bash

case $(uname) in
	FreeBSD)
		alias ls='ls -hFG'
	;;
esac

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ll='ls -l'
alias la='ls -A'
alias lla='ll -A'
alias j='jobs -l'
alias h='history 25'
alias g='git'
alias emc='emacsclient -a "" -nw'
alias emt='emacs -nw'

