#!/usr/bin/env bash

# If not running interactively, don't do anything
case $- in
	*i*) ;;
	*) return ;;
esac

export EDITOR=vim
export VISUAL=vim
export SVN_EDITOR='vim -u /etc/vim/vimrc'
export PAGER=less
export ROVER_OPEN=xdg-open
export PATH="$PATH:/usr/local/sbin:/usr/sbin:/sbin"
export PATH="$HOME/.local/bin:$PATH"

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# No history file for less(1)
export LESSHISTFILE=-

PS1='\u@\h \W\$ '

case "$TERM" in
	xterm-color|*-256color|rxvt-unicode)
        [[ -e /usr/local/share/git-core/contrib/completion/git-prompt.sh ]] && \
            . /usr/local/share/git-core/contrib/completion/git-prompt.sh

        [[ -e /usr/lib/git-core/git-sh-prompt ]] && \
            . /usr/lib/git-core/git-sh-prompt

        PS1='\[\e[33m\]\u@\h \[\e[39m\]\W $ '
        [[ $(type -t __git_ps1) == function ]] && \
            GIT_PS1_SHOWCOLORHINTS=true && \
            PROMPT_COMMAND='__git_ps1 "\[\e[33m\]\u@\h \[\e[39m\]\W" " $ "'
	;;
esac

# If this is an xterm set the title to "user@host dir"
case "$TERM" in
	xterm*|rxvt*)
		PS1="\[\e]0;\u@\h \W\a\]$PS1" ;;
esac

if ! shopt -oq posix; then
	if [ -f /usr/local/share/bash-completion/bash_completion.sh ]; then
		. /usr/local/share/bash-completion/bash_completion.sh
	elif [ -f /usr/share/bash-completion/bash_completion ]; then
		. /usr/share/bash-completion/bash_completion
	elif [ -f /etc/bash_completion ]; then
		. /etc/bash_completion
	fi
fi

if [ "$TERM" == "linux" ]; then
	# disable bell
	setterm --blength 0
fi

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias g='git'
alias y='yarn'
alias emc='emacsclient -a "" -nw'
alias emt='emacs -nw'
alias op='xdg-open'
complete -F _longopt op

if [ -f ~/.bash_local ]; then
	. ~/.bash_local
fi
