#!/usr/bin/env bash

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias g='git'
alias y='yarn'
alias emc='emacsclient -a "" -nw'
alias emt='emacs -nw'
alias op='xdg-open'
