#!/usr/bin/env bash

# If not running interactively, don't do anything
case $- in
	*i*) ;;
	*) return ;;
esac

export EDITOR=vim
export PAGER=less
export PATH="$HOME/.local/bin:$PATH"

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# No history file for less(1)
export LESSHISTFILE=-

PS1='\u@\h:\w\$ '

case "$TERM" in
	xterm-color|*-256color|rxvt-unicode)
		#PS1='\e[90m\u@\h:\e[39m\w$(__git_ps1 " (%s)") \$ '
		GIT_PS1_SHOWCOLORHINTS=true
		PROMPT_COMMAND='__git_ps1 "\[\e[90m\]\u@\h:\[\e[39m\]\w" " $ "'
	;;
esac

# If this is an xterm set the title to user@host:dir
case "$TERM" in
	xterm*|rxvt*)
		PS1="\[\e]0;\u@\h: \w\a\]$PS1" ;;
esac

if ! shopt -oq posix; then
	if [ -f /usr/local/share/bash-completion/bash_completion.sh ]; then
		. /usr/local/share/bash-completion/bash_completion.sh
	elif [ -f /usr/share/bash-completion/bash_completion ]; then
		. /usr/share/bash-completion/bash_completion
	elif [ -f /etc/bash_completion ]; then
		. /etc/bash_completion
	fi
fi

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

if [ "$TERM" == "linux" ]; then
	# disable bell
	setterm --blength 0
fi

if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi

if [ -f ~/.bash_local ]; then
	. ~/.bash_local
fi
