#!/bin/sh
cd
export PATH="$HOME/.local/bin:$PATH"
#dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY &

# disables x bell
xset b off
# disables x screen saver
xset s off -dpms

[ $(uname) = "FreeBSD" ] && my-brightness load

xsetroot -solid black # desktop background
runsvdir -P ~/my-runit &
exec dwm
