#!/bin/sh

set -e

backup="y"

files="/boot/loader.conf\
	/etc/devfs.rules\
	/etc/devd.conf\
	/etc/fstab\
	/etc/ipfw.rules\
	/etc/login.conf\
	/etc/profile\
	/etc/rc.conf\
	/etc/sysctl.conf\
	/usr/local/etc/X11/xorg.conf.d/keyboard-br.conf\
	/usr/local/etc/X11/xorg.conf.d/xorg.conf\
	/usr/local/etc/slim.conf\
	/etc/auto_master"

usage() {
    cat << EOF
usage: install.sh [options]

Without options: Make a backup of the configuration files

OPTIONS:
  -r    Restore the backup
  -l	List the files
  -h    Show this message
EOF
    exit $1
}

list_files(){
	echo "# Files to backup:"
	for file in $files; do
		echo "$file"
	done
	exit 0
}

## Parse command line switches
while getopts "rlh" option; do
    case "$option" in
        r) backup="n" ;;
        l) list_files ;;
        h) usage 0 ;;
        ?) usage 1 ;;
    esac
done

if [ $backup == "y" ]; then
	tar -cf backup.tar $files
else
	echo "Switching to user root"
	sudo -u root tar -xPf backup.tar -C /
fi
